config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :journals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'journals#index'
  get 'reflections/new', to: 'reflection#new', as: :new_reflection
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journal.rb
class Journal < ApplicationRecord
end

app/models/reflection.rb
class Reflection < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy]

  # GET /journals
  # GET /journals.json
  def index
    @journals = Journal.all
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        flash[:success] = 'Entry was successfully created.'
        format.html { redirect_to @journal }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        flash[:success] = 'Entry was successfully updated.'
        format.html { redirect_to @journal }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      flash[:success] = 'Entry was successfully destroyed.'
      format.html { redirect_to journals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_params
      params.require(:journal).permit(:title, :date, :entry)
    end
end

app/controllers/reflections_controller.rb
class ReflectionsController < ApplicationController
  before_action :set_reflection, only: [:show, :edit, :update, :destroy]

  # GET /reflections
  # GET /reflections.json
  def index
    @reflections = Reflection.all
  end

  # GET /reflections/1
  # GET /reflections/1.json
  def show
  end

  # GET /reflections/new
  def new
    @reflection = Reflection.new
  end

  # GET /reflections/1/edit
  def edit
  end

  # POST /reflections
  # POST /reflections.json
  def create
    @reflection = Reflection.new(reflection_params)

    respond_to do |format|
      if @reflection.save
        flash[:success] = 'Entry was successfully created.'
        format.html { redirect_to @reflection }
        format.json { render :show, status: :created, location: @reflection }
      else
        format.html { render :new }
        format.json { render json: @reflection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reflections/1
  # PATCH/PUT /reflections/1.json
  def update
    respond_to do |format|
      if @reflection.update(reflection_params)
        flash[:success] = 'Entry was successfully updated.'
        format.html { redirect_to @reflection }
        format.json { render :show, status: :ok, location: @reflection }
      else
        format.html { render :edit }
        format.json { render json: @reflection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reflections/1
  # DELETE /reflections/1.json
  def destroy
    @reflection.destroy
    respond_to do |format|
      flash[:success] = 'Entry was successfully destroyed.'
      format.html { redirect_to reflections_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reflection
      @reflection = Reflection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reflection_params
      params.require(:reflection).permit(:title, :date, :entry)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.erb
<%= form_for(@journal, html: {class: 'form-horizontal'}) do |f| %>
  <% if @journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
      <% @journal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :entry, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :entry, class: 'form-control' %>
    </div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Editing Journal</h1>

<%= render 'form', journal: @journal %>

<%= link_to 'Show', @journal %> |
<%= link_to 'Back', journals_path %>

app/views/journals/index.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'View journal', journals_path %></li>
  <li><%= link_to 'New entry', new_journal_path %></li>
  <li><%= link_to 'New reflection', new_reflection_path %></li>
</ul>

<p id="notice"><%= notice %></p>

<h1>Journals</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @journals.each do |journal| %>
      <tr class="active">
        <td>
          <span class="has-tooltip" data-toggle="tooltip" title="<%= "Created on #{journal.created_at.strftime("%m/%e/%Y at %w:%M %p")}, Last modified on #{journal.updated_at.strftime("%m/%e/%Y at %w:%M %p")}" %>">
            <%= journal.title %>
          </span>
        </td>
        <td><%= journal.date %></td>
        <td><% if journal.entry? %>
          <!-- Button trigger modal -->
          <button class="btn btn-link" data-toggle="modal" data-target="#journal-<%= journal.id %>-entry">
            View entry
          </button>

          <!-- Modal -->
          <div class="modal fade" id="journal-<%= journal.id %>-entry" tabindex="-1" role="dialog" aria-labelledby="journal-<%= journal.id %>-label" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title" id="journal-<%= journal.id %>-label">entry</h4>
                </div>
                <div class="modal-body">
                  <%= journal.entry %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        <% end %></td>
        <td><%= link_to 'Show', journal, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_journal_path(journal), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Destroy', journal, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h2>Reflections</h2>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Reflection</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reflections.each do |reflection| %>
      <tr class="active">
        <td><%= reflection.date %></td>
        <td>
          <!-- Button trigger modal -->
          <button class="btn btn-link" data-toggle="modal" data-target="#reflection-<%= reflection.id %>-entry">
            View reflection
          </button>

          <!-- Modal -->
          <div class="modal fade" id="reflection-<%= reflection.id %>-entry" tabindex="-1" role="dialog" aria-labelledby="reflection-<%= reflection.id %>-label" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title" id="journal-<%= journal.id %>-label">reflection</h4>
                </div>
                <div class="modal-body">
                  <%= reflection.entry %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        </td>
        <td><%= link_to 'Show', reflection, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_reflection_path(reflection), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Destroy', reflection, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_journal_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-pencil"></i> New Entry
<% end %>
<%= link_to new_reflection_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-pencil"></i> New Reflection
<% end %>

app/views/journals/new.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View journal', journals_path %></li>
  <li class="active"><%= link_to 'New Entry', new_journal_path %></li>
</ul>

<h1>New Entry</h1>

<%= render 'form', journal: @journal %>

<%= link_to 'Back', journals_path %>

app/views/journals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @journal.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @journal.date %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @journal.entry %>
</p>

<%= link_to 'Edit', edit_journal_path(@journal) %> |
<%= link_to 'Back', journals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'shared/navigation' %>
    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "alert alert-#{name}" %>
          <% end -%>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-3">
          <h3>What's on your mind?</h3>
        </div>
        <div class="col-xs-9">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-custom" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">MyJournal</a>
    </div>

    <ul class="nav navbar-nav pull-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            Hello! You are logged in. <%= current_user.name %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Profile', edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            <li class="divider"></li>
            <li><%= link_to 'Create an entry', new_journal_path %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to 'Log In', new_user_session_path %></li>
        <li class="divider"></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>